name = "HamiltonianSimDocs"
uuid = "e5bb7225-a469-4469-832c-1a8f9a5ad405"
version = "0.1.0"
authors = ["bischoff-m <bischoff_m@aim.com>"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.41.1"
