project:
  type: website
  output-dir: _site
website:
  title: "Port-Hamiltonian Simulator"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - basics.qmd
      - notation.qmd
      - LinearPHS.qmd
      - ControlofPHS.qmd
      - references.qmd
format:
  html:
    theme: cosmo
    toc: true
